spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring_example
    username: postgres
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true